# Generated by Django 5.1.5 on 2025-02-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RideBooking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="destination",
            field=models.CharField(
                choices=[
                    ("BLOCK-1", "B1"),
                    ("BLOCK-2", "B2"),
                    ("BLOCK-3", "B3"),
                    ("BLOCK-4", "B4"),
                    ("BLOCK-5", "B5"),
                    ("BLOCK-6", "B6"),
                    ("BLOCK-7", "B7"),
                    ("BLOCK-8", "B8"),
                    ("BLOCK-9", "B9"),
                    ("BLOCK-10", "B10"),
                    ("BLOCK-11", "B11"),
                    ("BLOCK-12", "B12"),
                    ("BLOCK-13", "B13"),
                    ("BLOCK-14", "B14"),
                    ("BLOCK-15", "B15"),
                ],
                default="B1",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_location",
            field=models.CharField(
                choices=[
                    ("BLOCK-1", "B1"),
                    ("BLOCK-2", "B2"),
                    ("BLOCK-3", "B3"),
                    ("BLOCK-4", "B4"),
                    ("BLOCK-5", "B5"),
                    ("BLOCK-6", "B6"),
                    ("BLOCK-7", "B7"),
                    ("BLOCK-8", "B8"),
                    ("BLOCK-9", "B9"),
                    ("BLOCK-10", "B10"),
                    ("BLOCK-11", "B11"),
                    ("BLOCK-12", "B12"),
                    ("BLOCK-13", "B13"),
                    ("BLOCK-14", "B14"),
                    ("BLOCK-15", "B15"),
                ],
                max_length=20,
            ),
        ),
    ]
