# Generated by Django 5.1.5 on 2025-02-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
